from pysnmp.hlapi import *
from pysnmp import hlapi
import quicksnmp
import psycopg2
import sys

con = psycopg2.connect("host='localhost' dbname='testdb' user='pythonspot' password='Dimas98@srg'")
cur = con.cursor()
#cur.execute("CREATE TABLE snmptest(Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, oid VARCHAR, location VARCHAR, uptime BIGINT)")

errorIndication, errorStatus, errorIndex, varBinds = next(
    getCmd(SnmpEngine(),
           CommunityData('public', mpModel=0),
           UdpTransportTarget(('demo.snmplabs.com', 161)),
           ContextData(),
           ObjectType(ObjectIdentity('SNMPv2-MIB', 'sysDescr', 0)))
)

if errorIndication:
    print(errorIndication)
elif errorStatus:
    print('%s at %s' % (errorStatus.prettyPrint(),
                        errorIndex and varBinds[int(errorIndex) - 1][0] or '?'))
else:
    for varBind in varBinds:
        print(' = '.join([x.prettyPrint() for x in varBind]))
print("\n\n")
print(varBinds)
print('')
uptime = quicksnmp.get('demo.snmplabs.com', ['.1.3.6.1.2.1.1.3.0'], hlapi.CommunityData('public', mpModel=0))
location = quicksnmp.get('demo.snmplabs.com', ['.1.3.6.1.2.1.1.6.0'], hlapi.CommunityData('public', mpModel=0))
for k, v in uptime.items():
    currentuptime = v
    print(("Up Time: {} days").format(v/60/60/24))
# We leave a blank line between the output of each interface
print('')
#quicksnmp.set('demo.snmplabs.com', {'.1.3.6.1.2.1.1.1.0': 'Test'}, hlapi.CommunityData('public', mpModel=0))


for k, v in location.items():
    currentlocation = str(v)
    print(("Location: {}").format(v))
# We leave a blank line between the output of each interface
print('')
stmt = "INSERT INTO snmptest(oid, location, uptime) VALUES(%s,%s,%s)"
cur.execute(stmt, ('demo.snmplabs.com', currentlocation, currentuptime))
#cur.execute("INSERT INTO snmptest(location, uptime) VALUES(?,?)")
con.commit()
con.close()